### ISSUE TITLE
sdl2.0.8 crashes with software rasterizer

### ISSUE THREAD

**Issue by codz01** [ev1313/Pascal-SDL-2-Headers#61] opened 2018-02-15 07:41 UTC
Hi 
i've built sdl2 from git yesterday ,  the surprise is if i use this new sdll2.dll , the app crashes if i use software rasterizer but with opengl or d3d9 it works ok !!

this is the example : 
program test;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}
{$apptype gui}
uses sdl2;
var
  m_window : PSDL_Window;
  m_renderer : PSDL_Renderer;
  event : TSDL_Event;
  running : boolean = true;
begin
  	
  SDL_Init( SDL_INIT_VIDEO );
  m_window := SDL_CreateWindow('test',SDL_WINDOWPOS_CENTERED,
                                    SDL_WINDOWPOS_CENTERED, 
                                    1024,600, SDL_WINDOW_SHOWN );
  m_renderer := SDL_CreateRenderer(m_window,-1,SDL_RENDERER_SOFTWARE );
  
  while (running) do begin
    if SDL_PollEvent(@event) > 0 then begin
       case event.type_ of
       SDL_QUITEV: begin
         running := false;
         end;
       end;
    end;
    SDL_SetRenderDrawColor( m_renderer, 40, 40, 50, 255 );
    SDL_RenderClear( m_renderer );  
    SDL_RenderPresent( m_renderer );
  end;
end.

![error](https://user-images.githubusercontent.com/10813427/36245537-6e2882d8-11e0-11e8-999e-8bac37a00177.png)

the line 27 point to SDL_RenderClear( m_renderer );   
any clue ? 
thanks

**Comment by codz01** [comment] 2018-02-15 08:57
i just rebuild sdl2 without sse , it works now 
seems problem of alignement between gcc&sse  and fpc

**Comment by suve** [comment] 2018-02-15 08:57
[FPC user manual](https://freepascal.org/docs-html/current/user/userap4.html) says that runtime error 216 is an Access Violation. This usually means referencing an invalid pointer. Can you add NIL-checks to see if `SDL_CreateWindow` and `SDL_CreateRenderer` calls do not fail?

Also, you can use a triple backtick ("\`\`\`") to put a code block in a comment; this makes it easier to read such stuff.  :)

**Comment by suve** [comment] 2018-02-15 08:58
Ah, right. There seems to be a bug in FPC currently where sometimes it produces bad alignments.

**Comment by ev1313** [comment] 2018-02-15 17:17
@suve got any link to the FPC bugtracker?

**Comment by suve** [comment] 2018-02-15 20:38
We've noticed a breakage on Fedora, where some FPC-compiled programs would crash with an Access Violation during cleanup (somewhere in `glibc` destructors). This was deemed to be caused by some misaligned data. Here's the link to the Red Hat Bugzilla ticket: [1526848](https://bugzilla.redhat.com/show_bug.cgi?id=1526848)

To be fair, I haven't checked if anyone reported this upstream. I'll look into that tomorrow.

**Comment by codz01** [comment] 2018-02-16 09:21
i tried with fpc 3.1.1 (trunk ), and seems there is no problem !! 
the problem was with fpc 3.0.0 and 3.0.4 
no need to fill a report :)

**Comment by codz01** [comment] 2018-02-16 13:43
the problem raised again  :( , even with fpc trunk 
this time with the function SDL_RenderFillRect .

**Comment by ev1313** [comment] 2018-04-05 01:18
is it still happening with updated fpc/lazarus?

**Comment by codz01** [comment] 2018-04-05 20:59
the last time i tried with fpc trunk Feb 16 , yes it happend 
but since sdl2.0.8 is officially released , i download the library's binary yesterday and seems no problem , but maybe they build it without sse !!

**Comment by ev1313** [comment] 2018-04-05 23:24
i'm closing this issue then, as I don't think this is an issue with the headers itself, but rather fpc. Feel free to keep us updated here, though.

**Closed by ev1313** 2018-04-05 23:24 UTC
